# Generated by Django 3.1.7 on 2021-04-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
