# Generated by Django 3.1.7 on 2021-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=8)),
                ('name_long', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name_first', models.CharField(max_length=30)),
                ('name_last', models.CharField(max_length=30)),
                ('is_instructor', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='profilepage.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
