# Generated by Django 3.2 on 2021-04-29 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('duser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name_first', models.CharField(max_length=30)),
                ('name_last', models.CharField(max_length=30)),
                ('is_instructor', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='profilepage.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
