# Generated by Django 3.1.7 on 2021-04-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_auto_20210415_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
    ]
