# Generated by Django 3.1.7 on 2021-05-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_db', '0004_auto_20210426_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
