# Generated by Django 3.2 on 2021-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_user', models.CharField(max_length=50)),
                ('other_user', models.CharField(max_length=50)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
