# Generated by Django 3.1.7 on 2021-04-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='receiver_uuid',
            new_name='from_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender_uuid',
            new_name='to_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
    ]
